export const qwertyToCmajorScale = {
    'Q': 'C4',
    'W': 'D4',
    'E': 'E4',
    'R': 'F4',
    'T': 'G4',
    'Y': 'A4',
    'U': 'B4',
    'I': 'C5',
    'O': 'D5',
    'P': 'E5',
    'A': 'F5',
    'S': 'G5',
    'D': 'A5',
    'F': 'B5',
    'G': 'C6',
    'H': 'D6',
    'J': 'E6',
    'K': 'F6',
    'L': 'G6',
    'Z': 'A6',
    'X': 'B6',
    //repeats - random
    'C': 'C4',
    'V': 'D5',
    'B': 'E6',
    'N': 'F4',
    'M': 'G5',
};

